//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyCalc2.Resx {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrencyCalc2.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alta-Soft doesn`t guarantee the accuracy of the displayed exchange rates. Before performing currency conversion transactions, check the current exchange rate..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Australian dollar.
        /// </summary>
        public static string AUD {
            get {
                return ResourceManager.GetString("AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bulgarian lev.
        /// </summary>
        public static string BGN {
            get {
                return ResourceManager.GetString("BGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brazilian real.
        /// </summary>
        public static string BRL {
            get {
                return ResourceManager.GetString("BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Canadian dollar.
        /// </summary>
        public static string CAD {
            get {
                return ResourceManager.GetString("CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Swiss franc.
        /// </summary>
        public static string CHF {
            get {
                return ResourceManager.GetString("CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chinese yuan renminbi.
        /// </summary>
        public static string CNY {
            get {
                return ResourceManager.GetString("CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alta Soft, 2018, All rights reserved..
        /// </summary>
        public static string CopyRightApp {
            get {
                return ResourceManager.GetString("CopyRightApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Czech koruna.
        /// </summary>
        public static string CZK {
            get {
                return ResourceManager.GetString("CZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Danish krone.
        /// </summary>
        public static string DKK {
            get {
                return ResourceManager.GetString("DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Euro.
        /// </summary>
        public static string EUR {
            get {
                return ResourceManager.GetString("EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exchange rate for.
        /// </summary>
        public static string ExchangeRateFor {
            get {
                return ResourceManager.GetString("ExchangeRateFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pound sterling.
        /// </summary>
        public static string GBP {
            get {
                return ResourceManager.GetString("GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hong Kong dollar.
        /// </summary>
        public static string HKD {
            get {
                return ResourceManager.GetString("HKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Croatian kuna.
        /// </summary>
        public static string HRK {
            get {
                return ResourceManager.GetString("HRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hungarian forint.
        /// </summary>
        public static string HUF {
            get {
                return ResourceManager.GetString("HUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indonesian rupiah.
        /// </summary>
        public static string IDR {
            get {
                return ResourceManager.GetString("IDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Israeli shekel.
        /// </summary>
        public static string ILS {
            get {
                return ResourceManager.GetString("ILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indian rupee.
        /// </summary>
        public static string INR {
            get {
                return ResourceManager.GetString("INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Icelandic krona.
        /// </summary>
        public static string ISK {
            get {
                return ResourceManager.GetString("ISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Japanese yen.
        /// </summary>
        public static string JPY {
            get {
                return ResourceManager.GetString("JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на South Korean won.
        /// </summary>
        public static string KRW {
            get {
                return ResourceManager.GetString("KRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currency converter.
        /// </summary>
        public static string MenuTitle0 {
            get {
                return ResourceManager.GetString("MenuTitle0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exchange rates.
        /// </summary>
        public static string MenuTitle1 {
            get {
                return ResourceManager.GetString("MenuTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string MenuTitle2 {
            get {
                return ResourceManager.GetString("MenuTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string MenuTitle3 {
            get {
                return ResourceManager.GetString("MenuTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mexican peso.
        /// </summary>
        public static string MXN {
            get {
                return ResourceManager.GetString("MXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Malaysian ringgit.
        /// </summary>
        public static string MYR {
            get {
                return ResourceManager.GetString("MYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currency converter.
        /// </summary>
        public static string NameApp {
            get {
                return ResourceManager.GetString("NameApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Central Bank of the Russian Federation.
        /// </summary>
        public static string NameSource1 {
            get {
                return ResourceManager.GetString("NameSource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на European Central Bank.
        /// </summary>
        public static string NameSource2 {
            get {
                return ResourceManager.GetString("NameSource2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Norwegian krone.
        /// </summary>
        public static string NOK {
            get {
                return ResourceManager.GetString("NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Zealand dollar.
        /// </summary>
        public static string NZD {
            get {
                return ResourceManager.GetString("NZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на on.
        /// </summary>
        public static string OnLower {
            get {
                return ResourceManager.GetString("OnLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Philippine piso.
        /// </summary>
        public static string PHP {
            get {
                return ResourceManager.GetString("PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a number.
        /// </summary>
        public static string PickerName {
            get {
                return ResourceManager.GetString("PickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Polish zloty.
        /// </summary>
        public static string PLN {
            get {
                return ResourceManager.GetString("PLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Romanian leu.
        /// </summary>
        public static string RON {
            get {
                return ResourceManager.GetString("RON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian rouble.
        /// </summary>
        public static string RUB {
            get {
                return ResourceManager.GetString("RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Swedish krona.
        /// </summary>
        public static string SEK {
            get {
                return ResourceManager.GetString("SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Singapore dollar.
        /// </summary>
        public static string SGD {
            get {
                return ResourceManager.GetString("SGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data source.
        /// </summary>
        public static string TextSourceLabel {
            get {
                return ResourceManager.GetString("TextSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thai baht.
        /// </summary>
        public static string THB {
            get {
                return ResourceManager.GetString("THB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turkish lira.
        /// </summary>
        public static string TRY {
            get {
                return ResourceManager.GetString("TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на US dollar.
        /// </summary>
        public static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на South African rand.
        /// </summary>
        public static string ZAR {
            get {
                return ResourceManager.GetString("ZAR", resourceCulture);
            }
        }
    }
}
